---
abstract: 'RT-Extension-ManageAutoCreatedUsers Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ManageAutoCreatedUsers
no_index:
  directory:
    - html
    - inc
    - static
    - xt
  package:
    - RT::User
requires:
  Class::Method::Modifiers: 0
  Module::Runtime: 0
  RT::Extension::MergeUsers: 0
  perl: 5.10.1
resources:
  homepage: https://github.com/bestpractical/rt-extension-manageautocreatedusers/tree
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-extension-manageautocreatedusers.git
version: '0.12'
x_module_install_rtx_version: '0.37'
x_requires_rt: 4.2.0
x_requires_rt_plugins:
  - RT::Extension::MergeUsers
